### ISSUE TITLE
Library Installation

### ISSUE THREAD

**Issue by danishhusain** [Navigine/react-native-navigine-example#2]
* What went wrong:
Could not determine the dependencies of task ':react-native-navigine:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':react-native-navigine:debugCompileClasspath'.
   > Could not find com.github.Navigine:Indoor-Navigation-Android-Mobile-SDK-2.0:20231105.
     Required by:
         project :react-native-navigine
         
         
Getting error as anyone available who can help me ? Its very important for me.

**Comment by PavelTychinin** [comment]
Hi, thanks for issue.
We released new sdk version 1.1.3. Can you try it?

**Comment by PavelTychinin** [comment]
Hi. Try version 1.1.5. Clean project and build again
